name: tropidash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - bqplot=0.12.40
  - branca=0.6.0
  - cfgrib=0.9.10.4
  - flask=2.3.3
  - eccodes=2.31.0
  - ecmwf-opendata=0.3.3
  - haversine=2.8.0
  - ipywidgets=8.1.0
  - ipyleaflet=0.17.3
  - ipympl=0.9.3
  - jupyterlab=4.0.5
  - localtileserver=0.7.1
  - matplotlib=3.7.1
  - numpy=1.25.2
  - pandas=2.1.0
  - pip=23.2.1
  - pdbufr=0.11.0
  - rasterio=1.3.8
  - requests=2.31.0
  - rioxarray=0.15.0
  - scipy=1.11.2
  - voila=0.5.2
  - xarray=2023.8.0
  - pip:
      - datetime==5.5
